#!/usr/bin/env python3
import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored



def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet @screen_name")
        
    tweetlist = helpers.get_user_timeline(sys.argv[1])
    
    if tweetlist == None:
        sys.exit("{} is private or does not exist".format(sys.argv[1]))
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
        
    # analyze tweet    
    for tweet in tweetlist:
        
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))
    

if __name__ == "__main__":
    main()
